#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : minimodem
Version  : 0.24.1
Release  : 4
URL      : https://github.com/kamalmostafa/minimodem/archive/minimodem-0.24-1.tar.gz
Source0  : https://github.com/kamalmostafa/minimodem/archive/minimodem-0.24-1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: minimodem-bin
Requires: minimodem-doc
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(fftw3f)
BuildRequires : pkgconfig(libpulse-simple)
BuildRequires : pkgconfig(sndfile)

%description
minimodem - general-purpose software audio FSK modem
Minimodem is a command-line program which decodes (or generates) audio
modem tones at any specified baud rate, using various framing protocols.
It acts a general-purpose software FSK modem, and includes support for
various standard FSK protocols such as Bell103, Bell202, RTTY, TTY/TDD,
NOAA SAME, and Caller-ID.

%package bin
Summary: bin components for the minimodem package.
Group: Binaries

%description bin
bin components for the minimodem package.


%package doc
Summary: doc components for the minimodem package.
Group: Documentation

%description doc
doc components for the minimodem package.


%prep
%setup -q -n minimodem-minimodem-0.24-1
pushd ..
cp -a minimodem-minimodem-0.24-1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517765627
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%reconfigure --disable-static
make  %{?_smp_mflags}
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
%reconfigure --disable-static    --libdir=/usr/lib64/haswell --bindir=/usr/bin/haswell
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1517765627
rm -rf %{buildroot}
pushd ../buildavx2/
%make_install
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/haswell/minimodem
/usr/bin/minimodem

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
